# Generated by Django 4.2.3 on 2024-02-09 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Liste',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Eintrag',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=50)),
                ('done', models.BooleanField()),
                ('listid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liste.liste')),
            ],
        ),
    ]
