# Generated by Django 4.2.3 on 2024-02-10 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liste', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eintrag',
            name='description',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='eintrag',
            name='type',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
