# Generated by Django 5.0.1 on 2024-02-13 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liste', '0003_alter_eintrag_description_alter_eintrag_listid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eintrag',
            old_name='description',
            new_name='Beschreibung',
        ),
        migrations.RenameField(
            model_name='liste',
            old_name='name',
            new_name='Name',
        ),
        migrations.RemoveField(
            model_name='eintrag',
            name='type',
        ),
        migrations.AlterField(
            model_name='listselect',
            name='listid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liste.liste'),
        ),
    ]
